const path = require("path");

module.exports = Object.freeze({
	WHATSAPP_URL      : "https://web.whatsapp.com",
	BROWSER_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
	BROWSER_ARGS      : [
		"--app=https://web.whatsapp.com",
		"--disable-gpu",
		"--renderer",
		"--no-sandbox",
		"--no-service-autorun",
		"--no-experiments",
		"--no-default-browser-check",
		"--disable-webgl",
		"--disable-threaded-animation",
		"--disable-threaded-scrolling",
		"--disable-in-process-stack-traces",
		"--disable-histogram-customizer",
		"--disable-gl-extensions",
		"--disable-extensions",
		"--disable-composited-antialiasing",
		"--disable-canvas-aa",
		"--disable-3d-apis",
		"--disable-accelerated-2d-canvas",
		"--disable-accelerated-jpeg-decoding",
		"--disable-accelerated-mjpeg-decode",
		"--disable-app-list-dismiss-on-blur",
		"--disable-accelerated-video-decode",
		"--num-raster-threads=1",
	],
	BROWSER_DATA_DIR  : path.join(`${process.cwd()}\\src\\bin`, "chromium-data"),
	BROWSER_PATH_DIR  : `${process.cwd()}\\src\\bin`,
	SETTINGS_FILE     : 'settings.json',
	PATH_WAPI         : `${process.cwd()}\\src\\lib\\WAPI.js`,
	PATH_INJECT       : `${process.cwd()}\\src\\lib\\INJECT.js`,
	PATH_CONFIG       : `${process.cwd()}\\src\\config\\index.js`,
	PATH_STYLES       : `${process.cwd()}\\src\\config\\styles.css`,
	PATH_STYLES_DARK  : `${process.cwd()}\\src\\config\\styles-dark.css`,
});
